@startuml

skinparam classAttributeIconSize 0

class CoachProfile {
    +Integer userId
    +String realName
    +String profileDescription
    +Integer coachedSports
    +Float rating
    +Boolean isActive
}

@enduml
