@startuml
|用户|
start
:进入登录界面;
if (选择注册?) then (是)
  :进入注册界面;
  :填写注册信息;
  :提交注册;
  :返回登录界面;
else (否)
  :直接登录;
  :输入用户名和密码;
  if (验证通过?) then (是)
    :登录成功;
    :选择功能;
    fork
      :购买火车票;
      :选择火车;
      :生成购票记录;
    fork again
      :查看已购火车票;
      :显示购票历史;
    fork again
      :修改个人信息;
      :编辑并提交修改;
    end fork
    if (是否是root用户?) then (是)
      :进入管理员界面;
      :添加/修改/删除火车信息;
    else (否)
      :普通用户操作完成;
    endif
  else (否)
    :登录失败;
  endif
end
stop
@enduml
